

pacbio:
	../../pasa-salraa --bam pacbio.PBLR.bam --genome ref_genome.fa --CPU 4 --outputfile pasa-salraa.pbio.gtf


illumina:
	../../pasa-salraa --bam illumina.bam --genome ref_genome.fa --CPU 4 --outputfile pasa-salraa.illumina.gtf


both:
	../../pasa-salraa  --bam illum_n_pacbio.bam --genome ref_genome.fa --CPU 4
