

pbio:
	../../pasa-salraa --bam pacbioccsminimap.minig.PBLR.bam --genome minig.fa --outputfile pasa-salraa.pbio.gtf


illumina:
	../../pasa-salraa --bam illumina_regular_frags.minig.bam --genome minig.fa --outputfile pasa-salraa.illumina.gtf


both:
	../../pasa-salraa --bam illumina_plus_pacbio.merged.bam --genome minig.fa --outputfile pasa-salraa.both.gtf


