

run_small:
	../pasa-salraa --bam alignments.1-50k.bam --genome minigenome.fa --CPU 4 --outputfile pasa-salraa.small.gtf


run_large:
	../pasa-salraa --bam alignments.bam --genome minigenome.fa --CPU 4 --outputfile pasa-salraa.large.gtf



clean:
	./cleanme.pl

